services:
  arm64-headless-builder:
    image: ghcr.io/tonalflex/elk-audio-os-builder:latest
    container_name: arm64-headless-builder
    platform: linux/amd64 # Required for Apple Silicon
    volumes:
      - ./plugin:/home/yoctouser/plugin
      - ./script:/home/yoctouser/script
      - ./bin:/home/yoctouser/bin
    working_dir: /home/yoctouser/script
    command: "./build-arm64-headless.sh"
