services:
  elk-plugin-builder:
    image: ghcr.io/tonalflex/elk-audio-os-builder:latest
    container_name: elk-plugin-builder
    platform: linux/amd64 # Apple Silicon
    volumes:
      - ./plugin:/home/yoctouser/plugin
      - ./script:/home/yoctouser/script
      - ./output:/home/yoctouser/output
    working_dir: /home/yoctouser/script
    command: "./build-elk-plugin.sh"
